layers = 12
s = 512 # sentence length
h = 768 # hidden state size of qkv
mutihead_num = 12 # multihead number
output_h = 768 # output hidden size
r = 12 # rank
inference_type = 0 # 0 for loro, 1 for full matrix
classification_num = 2 # head size
ffn_h =3072 # intermediate hidden state size
