layers = 28
s = 256 # sentence length
h = 3584 # hidden state size of qkv
mutihead_num = 28 # multihead number
group_num = 4 # group query attention
output_h = 3584 # output hidden size
r = 36 # rank
inference_type = 0 # 0 for loro, 1 for full matrix
classification_num = 151936 # head size
ffn_h = 18944 # intermediate hidden state size
